services:
  api:
    command: npm run dev

  mongo-exp:
    image: mongo-express:0.54.0
    container_name: mongo-e
    restart: always
    ports:
      - ${MONGO_EXP_PORT}:${MONGO_EXP_PORT}
    depends_on:
      - ${MONGO_CONTAINER}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_SERVER
      - ME_CONFIG_MONGODB_PORT